// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu2pKtjdOBNGA7-oLNVigkgDNpeH1W1NU',
    appId: '1:760971451432:web:6a726876faa6a33c52a91d',
    messagingSenderId: '760971451432',
    projectId: 'flutterfire-ui-codelab-4214d',
    authDomain: 'flutterfire-ui-codelab-4214d.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-4214d.appspot.com',
    measurementId: 'G-ZQJCC561SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_e0lHb-fQYryJuAdvYe_KwZwMy5J32fI',
    appId: '1:760971451432:android:3aae4d7a6d4b38e252a91d',
    messagingSenderId: '760971451432',
    projectId: 'flutterfire-ui-codelab-4214d',
    storageBucket: 'flutterfire-ui-codelab-4214d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpPSs40M96lBS8f9fpJInIqkrQiCCxxh0',
    appId: '1:760971451432:ios:bad89f0876e6cdb252a91d',
    messagingSenderId: '760971451432',
    projectId: 'flutterfire-ui-codelab-4214d',
    storageBucket: 'flutterfire-ui-codelab-4214d.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpPSs40M96lBS8f9fpJInIqkrQiCCxxh0',
    appId: '1:760971451432:ios:8bc228808fcebd1f52a91d',
    messagingSenderId: '760971451432',
    projectId: 'flutterfire-ui-codelab-4214d',
    storageBucket: 'flutterfire-ui-codelab-4214d.appspot.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
